### PR TITLE
Update lodestar cli flags

### PR DESCRIPTION
**Pull request by wemeetagain**
Marking as draft until we test it locally

cc @dapplion

### CODE REVIEW

**Comment by wemeetagain** [comment]
also cc @faithtosin

**Comment by dapplion** [comment]
Looks good! @parithosh

**Comment by parithosh** [comment]
ooo thanks! missed updating the flags here!

Could this be merged? @amirrustam @mieubrisse

**Comment by dapplion** [comment]
Ping

**Review by mieubrisse — APPROVED** [review]
Looks good! Just need to add a `docs/changelog.md` entry under the `# TBD` header and then good to go

**Comment by gbouv** [comment]
I think all of this has been included in @parithosh PR #137, which is now merged. Unless I'm missing something, this should be good to close now

**Comment by dapplion** [comment]
> 

Yes looks good

**Pull request closed without merging**
